# Generated by Django 3.2.9 on 2022-02-10 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_quantite', models.CharField(choices=[('g', 'gramme'), ('L', 'Litre'), ('mL', 'mL'), ('NBR', 'Nbre')], default='NBR', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Est_Prive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField()),
                ('Ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recette.ingredient')),
                ('Recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recette.recette')),
            ],
        ),
    ]
