# Generated by Django 4.0.2 on 2022-03-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='nom_ingredient',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
