# Generated by Django 3.2.9 on 2022-02-10 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frigo', '0001_initial'),
        ('recette', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('Regime', models.CharField(choices=[('OMni', 'Omnivore'), ('VeGa', 'Vegan'), ('VeGe', 'Vegétarien')], default='OMni', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Possede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paramètres.personne')),
                ('frigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frigo.frigo')),
            ],
        ),
        migrations.CreateModel(
            name='Carnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Favori', models.BooleanField(default=False)),
                ('Personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paramètres.personne')),
                ('Recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recette.recette')),
            ],
        ),
        migrations.CreateModel(
            name='aimepas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recette.ingredient')),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paramètres.personne')),
            ],
        ),
    ]
