# Generated by Django 3.2.9 on 2022-02-10 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frigo', '0001_initial'),
        ('recette', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('frigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frigo.frigo')),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recette.recette')),
            ],
        ),
    ]
