# Generated by Django 3.2.9 on 2022-02-10 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recette', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_frigo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='contient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField()),
                ('date_achat', models.DateField(auto_now=True)),
                ('date_de_peremption', models.DateField()),
                ('frigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frigo.frigo')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recette.ingredient')),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recette.recette')),
            ],
        ),
    ]
